language: php

php:
  - 5.4
  - 5.5
  - hhvm

before_script:
  - composer install
  - cd tests

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml
  - php vendor/bin/coveralls -v